### ISSUE TITLE
Wrong link to ACCORD documentation

### ISSUE THREAD

**Issue by nataschake** [Accord-Project/RegulationTransformationTool#1]
@beachtom Hi, I think you occasionally mislead to http://documentation.accordproject.eu?
these are the errors:
![image](https://github.com/user-attachments/assets/9a054e96-b651-49b8-b67e-4ebc1f79b65a)

So the first link in the README should be (I think) https://accord-project.github.io/ACCORD-Documentation ?
I can correct but please confirm

**Comment by beachtom** [comment]
Yes I am awaiting on OGC to set this up
