### ISSUE TITLE
RFT grammar railroad diagram

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accord-Project/RegulationTransformationTool#2]
@Gonsco @beachtom 
https://github.com/Accord-Project/ACCORD-Documentation/blob/main/docs/process.md#accord-bcrl-expressions shows some syntax diagrams. They are very useful, but made by hand.

I used https://www.bottlecaps.de/ebnf-convert/
to convert https://raw.githubusercontent.com/Accord-Project/RegulationTransformationTool/refs/heads/main/src/main/antlr4/Accord.g4 to EBNF,
and then https://www.bottlecaps.de/rr/ui to visualize it.

The result is [RFT-grammar.xhtml.txt](https://github.com/user-attachments/files/18079037/RFT-grammar.xhtml.txt) (rename to html to view it). It includes embedded SVG, so you can search by name.
Consider adding it to the repo, and offering it as an alternative grammar diagram (more precise, but harder to understand). You can add a direct view link like https://rawgit2.com/VladimirAlexiev/shacl/shaclc-grammars/shacl-compact-syntax/grammar/shaclc-ANTLR.html

Potential problems:
- the grammar isn't marked to start at `accordRules`. The first production is `bOp` (maybe it's first alphabetically)
- there is a rule `_:` which just refers to `WS` and is not referenced by anything. But maybe that's how whitespace is designated in ANTLR, or it's an artefact of the conversion
![image](https://github.com/user-attachments/assets/2b6181f5-6089-4a57-bdc8-cd5cb24e4ead)

**Comment by beachtom** [comment]
this is sorted - we now autogenerate a railroad diagram
